### PR TITLE
Update Robolectric to latest version (3.1.4)

### PR DESCRIPTION
**Pull request by mr-archano**
### Task Requested ###

The version of Robolectric used in tests is quite old (2.4).

### Solution implemented ###

Updated Robolectric dependency to 3.1.4. Amended the existing tests to deal with the changes in the Robolectric API.

#### Screenshots

No UI changes, therefore no screenshots.

### CODE REVIEW

**Comment by mr-archano** [comment]
@hal9002 retest this please 🎱

**Comment by mr-archano** [comment]
@hal9002 retest this please 🎱

**Comment by mr-archano** [comment]
@hal9002 retest this please 🎱

**Comment by juankysoriano** [comment]
Thanks @mr-archano a lot! 

That was in our TODO list, remember @eduardb ?? 😂 

Just resolved the conflicts with `master` and will merge once 💚 .

We are planning a release today that will fix some potential issues with Android `7.1`

**Pull request merged**
