### PR TITLE
Fix MethodNotFoundException issue #29

### PR DESCRIPTION
**Pull request by meierjan**
### Task Requested ###

fixed bug in android 7.1 (https://github.com/novoda/simple-chrome-custom-tabs/issues/29) 

### Solution implemented ###

updated dependencies

### CODE REVIEW

**Comment by stefanhoth** [comment]
Can one of the admins review this PR?

**Comment by meierjan** [comment]
To test it: 
https://jitpack.io/#meierjan/simple-chrome-custom-tabs-1/310d77f42e

I tested it on a Nexus 5X with Android 7.1.1

**Comment by alexstyl** [comment]
I can confirm that updating the dependencies fixes the issue
👍 from me

cc @juankysoriano for the final saying 😉

**Comment by juankysoriano** [comment]
Thanks @meierjan , I will take a look into this shortly and do a new release.

**Comment by juankysoriano** [comment]
LGTM, Thanks @meierjan

**Pull request merged**
