### PR TITLE
Remove notils library

### PR DESCRIPTION
**Pull request by CoreFloDev**
### Task Requested ###

Removing the Notils dependencies as it is used only to get the DeveloperError.

### Solution implemented ###

Removed the developerError and replaced it by an IllegalStateException

No updated tests only

Screenshots

No UI changes

### CODE REVIEW

**Comment by ataulm** [comment]
Ok to test

**Comment by ataulm** [comment]
test this please

**Comment by CoreFloDev** [comment]
Cheers @ataulm Can you also please make a release of it? or I can do it if you don't have time

**Comment by rock3r** [comment]
Leaving to @ataulm

**Comment by ataulm** [comment]
let me check the job, something funky with status checks.

Do you have the ability to make releases? 🤔

**Comment by rock3r** [comment]
I don't, or at least never done one and not familiar with the process. I think the issue with the job is that you might have custom status reporting on the PRB and that is a bit messy. You should be able to ship anyway.

**Comment by ataulm** [comment]
No, I was asking @CoreFloDev if they have the ability to make releases.

I would rather wait until tomorrow to make a release - I'm not the most active on this project so I don't know if the maintainers have plans to ship other things also.

**Comment by ataulm** [comment]
Thanks for your contribution!

**Comment by ataulm** [comment]
@CoreFloDev it's in 0.1.6

**Comment by CoreFloDev** [comment]
Perfect man thanks for being so reactive

**Pull request merged**
